FROM ruby:2.7.1

RUN apt update && apt install -y nodejs npm

# set /app as application folder inside the container
RUN mkdir /app
WORKDIR /app

# copy gemfiles to application folder
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem install bundler -v 2.2.29
ENV BUNDLER_VERSION=2.2.29

RUN npm install -g yarn

# install all app dependencies
RUN bundle install

# copy all the application files to the container
COPY . .

# entrypoint script with command execution and server.pid fix
COPY entrypoint_prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint_prod.sh
ENTRYPOINT ["entrypoint_prod.sh"]

# set timezone
ENV TZ=America/Asuncion
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# expose the port
EXPOSE 3000

# start rails server
CMD ["rails", "server", "-b", "0.0.0.0", "-e", "production"]

