// seeds.js - JS translation of db/seeds.rb for reference only (not executed)
// This file mirrors the key structures: Presentations, Categories/Subcategories, Brands, Varieties, Products, Discounts, MeasurementUnits.

module.exports = {
  admin: { email: 'desarrollo@creadores.com.py', password: 'dameunpassword' },
  presentations: [
    { name_es: 'Bidón de 4L', active: true },
    { name_es: 'Bolsa de 80g', active: true },
    { name_es: 'Bolsa de 200g', active: true },
    { name_es: 'Bolsa de 400g', active: true },
    { name_es: 'Bolsa de 600g', active: true },
    { name_es: 'Bolsa de 800g', active: true },
    { name_es: 'Bolsa de 2Kg', active: true },
    { name_es: 'Bolsa de 3,4Kg', active: true },
    { name_es: 'Bolsa de 5Kg', active: true },
    { name_es: 'Bolsa de 10Kg', active: true },
    { name_es: 'Bolsa de 150g', active: true },
    { name_es: 'Bolsa de 1Kg', active: true },
    { name_es: 'Bolsa de 3Kg', active: true },
    { name_es: 'Pan de 60g', active: true },
    { name_es: 'Pan de 100g', active: true },
    { name_es: 'Pan de 200g', active: true },
    { name_es: 'Pack 10 x 40g', active: true },
    { name_es: 'Barra de 500g', active: true },
    { name_es: 'Barra de 1000g', active: true },
    { name_es: 'Pan de 180g', active: true },
    { name_es: 'Pan de 130g', active: true },
    { name_es: 'Pack de 5 x 180g', active: true },
    { name_es: 'Pan de 250g', active: true },
    { name_es: 'Pan de 230g', active: true },
  ],
  categories: [
    {
      name_es: 'Cuidado de las Prendas',
      active: true,
      subcategories: [
        { name_es: 'Bolsas', active: true },
        { name_es: 'Desodorante', active: true },
        { name_es: 'Detergente', active: true },
        { name_es: 'Lavandina', active: true },
        { name_es: 'Trapos', active: true },
      ],
    },
    {
      name_es: 'Higiene Personal',
      active: true,
      subcategories: [
        { name_es: 'Coco Puro', active: true },
        { name_es: 'Jabón de lavar', active: true },
        { name_es: 'Jabón en polvo', active: true },
        { name_es: 'Jabón prensado', active: true },
        { name_es: 'Suavizante', active: true },
      ],
    },
    {
      name_es: 'Limpieza y Desinfeccion del Hogar',
      active: true,
      subcategories: [
        { name_es: 'Coco Puro', active: true },
        { name_es: 'Tocador', active: true },
      ],
    },
  ],
  brands: [
    { name: 'Cavallaro', active: true, order: 1 },
    { name: 'Pixol', active: true, order: 2 },
    { name: 'Agricultor', active: true, order: 3 },
    { name: 'Obrero', active: true, order: 4 },
    { name: 'C', active: true, order: 5 },
    { name: 'C2', active: true, order: 6 },
    { name: 'Guairá Extra', active: true, order: 7 },
    { name: 'Guairá Deluxe', active: true, order: 8 },
    { name: 'Coco Puro', active: true, order: 9 },
    { name: 'Insuperable', active: true, order: 10 },
    { name: 'Guairá Opti-System', active: true, order: 11 },
    { name: 'gliCrina', active: true, order: 12 },
    { name: 'Sole Mio', active: true, order: 13 },
    { name: 'Cavallaro Premium', active: true, order: 14 },
  ],
  varieties: [
    { name_es: 'Azahar', active: true, color: '#258f00' },
    { name_es: 'Lavanda', active: true, color: '#ffd600' },
    { name_es: 'Uva', active: true, color: '#7d00c9' },
    // ... (ver db/seeds.rb para lista completa)
  ],
  measurement_units: [
    { code: 'CJ', name: 'Caja' },
    { code: 'DSP', name: 'Display' },
    { code: 'PCK', name: 'Pack' },
    { code: 'ROL', name: 'Rollo' },
    { code: 'UN', name: 'Unidad' },
  ],
  amount_discounts: [
    { min_amount: 20000, max_amount: 65000, discount_rate: 5, begin_date: '2019-01-01', end_date: '2050-31-12' },
    { min_amount: 65001, max_amount: 200000, discount_rate: 10, begin_date: '2019-01-01', end_date: '2050-31-12' },
    { min_amount: 200001, max_amount: 500000, discount_rate: 15, begin_date: '2019-01-01', end_date: '2050-31-12' },
    { min_amount: 500001, max_amount: 999999999, discount_rate: 25, begin_date: '2019-01-01', end_date: '2050-31-12' },
  ],
};
